<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('e_h_s_events', function (Blueprint $table) {
            $table->id();
            $table->text('initiator_id')->nullable();
            $table->text('division_id')->nullable();
            $table->text('division_code')->nullable();
            $table->text('intiation_date')->nullable();
            $table->text('status')->nullable();
            $table->text('stage')->nullable();
            $table->text('form_type')->nullable();
            $table->text('record')->nullable();
            $table->text('record_number')->nullable();
            $table->integer('parent_id')->nullable();
            $table->text('parent_type')->nullable();
            $table->text('assign_to')->nullable();
            $table->text('due_date')->nullable();
            $table->longText('short_description')->nullable();
            $table->text('Type')->nullable();
            $table->text('Incident_Sub_Type')->nullable();
            $table->text('Date_Occurred')->nullable();
            $table->text('Time_Occurred')->nullable();
            $table->longText('Attached_File')->nullable();
            $table->text('Similar_Incidents')->nullable();
            $table->text('Date_Of_Reporting')->nullable();
            $table->text('Reporter')->nullable();
            $table->longText('Description')->nullable();    
            $table->longText('Immediate_Actions')->nullable();
            $table->text('Accident_Type')->nullable();
            $table->text('OSHA_Reportable')->nullable();
            $table->text('First_Lost_Work_Date')->nullable();
            $table->text('Last_Lost_Work_Date')->nullable();
            $table->text('First_Restricted_Work_Date')->nullable();
            $table->text('Last_Restricted_Work_Date')->nullable();
            $table->text('Vehicle_Type')->nullable();
            $table->text('Vehicle_Number')->nullable();
            $table->text('Litigation')->nullable();
            $table->text('Department')->nullable();
            $table->text('Employees_Involved')->nullable();
            $table->text('Involved_Contractors')->nullable();
            $table->text('Attorneys_Involved')->nullable();
            $table->text('Lead_Investigator')->nullable();
            $table->text('Line_Operator')->nullable();
            $table->text('Reporter2')->nullable();
            $table->text('Supervisor')->nullable();
            $table->text('Unsafe_Situation')->nullable();
            $table->text('Safeguarding_Measure_Taken')->nullable();
            $table->text('Environmental_Category')->nullable();
            $table->text('Special_Weather_Conditions')->nullable();
            $table->text('Source_Of_Release_Or_Spill')->nullable();
            $table->text('Cause_Of_Release_Or_Spill')->nullable();
            $table->longText('Threat_Caused_By_Release_Spill')->nullable();
            $table->text('Environment_Evacuation_Ordered')->nullable();
            $table->text('Date_Samples_Taken')->nullable();
            $table->text('Agencys_Notified')->nullable();
            $table->text('Fire_Category')->nullable();
            $table->text('Fire_Evacuation_Ordered')->nullable();
            $table->text('Combat_By')->nullable();
            $table->longText('Fire_Fighting_Equipment_Used')->nullable();
            $table->text('zone')->nullable();
            $table->text('country')->nullable();
            $table->text('state')->nullable();
            $table->text('city')->nullable();
            $table->text('Site_Name')->nullable();
            $table->text('Building')->nullable();
            $table->text('Floor')->nullable();
            $table->text('Room')->nullable();
            $table->longText('Location')->nullable();
            $table->text('Victim')->nullable();
            $table->text('Medical_Treatment')->nullable();
            $table->text('Victim_Position')->nullable();
            $table->text('Victim_Relation_To_Company')->nullable();
            $table->text('Hospitalization')->nullable();
            $table->text('Hospital_Name')->nullable();
            $table->text('Date_Of_Treatment')->nullable();
            $table->text('Victim_Treated_By')->nullable();
            $table->longText('Medical_Treatment_Description')->nullable();
            $table->text('Injury_Type')->nullable();
            $table->text('Number_Of_Injuries')->nullable();
            $table->text('Type_Of_Injuries')->nullable();
            $table->text('Injured_Body_Parts')->nullable();
            $table->text('Type_Of_Illness')->nullable();
            $table->text('Permanent_Disability')->nullable();
            $table->text('Damage_Category')->nullable();
            $table->text('Related_Equipment')->nullable();
            $table->text('Estimated_Amount_Of_Damage')->nullable();
            $table->text('Currency')->nullable();
            $table->text('Insurance_Company_Involved')->nullable();
            $table->text('Denied_By_Insurance_Company')->nullable();
            $table->longText('Damage_Details')->nullable();
            $table->text('Actual_Amount_Of_Damage')->nullable();
            $table->text('Currency2')->nullable();
            $table->longText('Investigation_Summary')->nullable();
            $table->longText('Conclusion')->nullable();
            $table->longText('root_cause_methodology')->nullable();
            $table->longText('Root_Cause_Description')->nullable();
            $table->text('Safety_Impact_Probability')->nullable();
            $table->text('Safety_Impact_Severity')->nullable();
            $table->text('Legal_Impact_Probability')->nullable();
            $table->text('Legal_Impact_Severity')->nullable();
            $table->text('Business_Impact_Probability')->nullable();
            $table->text('Business_Impact_Severity')->nullable();
            $table->text('Revenue_Impact_Probability')->nullable();
            $table->text('Revenue_Impact_Severity')->nullable();
            $table->text('Brand_Impact_Probability')->nullable();
            $table->text('Brand_Impact_Severity')->nullable();
            $table->text('Safety_Impact_Risk')->nullable();
            $table->text('Legal_Impact_Risk')->nullable();
            $table->text('Business_Impact_Risk')->nullable();
            $table->text('Revenue_Impact_Risk')->nullable();
            $table->text('Brand_Impact_Risk')->nullable();
            $table->text('Impact')->nullable();
            $table->longText('Impact_Analysis')->nullable();
            $table->longText('Recommended_Actions')->nullable();
            $table->longText('Comments2')->nullable();
            $table->text('Direct_Cause')->nullable();
            $table->text('Safeguarding_Measure_Taken2')->nullable();
            $table->text('severity_rate')->nullable();
            $table->text('occurrence')->nullable();
            $table->text('detection')->nullable();
            $table->text('rpn')->nullable();
            $table->longText('Risk_Analysis')->nullable();
            $table->text('Critically')->nullable();
            $table->text('Inform_Local_Authority')->nullable();
            $table->text('Authority_Type')->nullable();
            $table->text('Authority_Notified')->nullable();
            $table->text('Other_Authority')->nullable();

            $table->text('ehsEvent_id')->nullable();

            $table->longtext('risk_factor')->nullable();
            $table->longtext('risk_element')->nullable();
            $table->longtext('problem_cause')->nullable();
            $table->longtext('existing_risk_control')->nullable();
            $table->longtext('initial_severity')->nullable();
            $table->longtext('initial_detectability')->nullable();
            $table->longtext('initial_probability')->nullable();
            $table->longtext('initial_rpn')->nullable();
            $table->longtext('risk_control_measure')->nullable();
            $table->longtext('residual_severity')->nullable();
            $table->longtext('residual_probability')->nullable();
            $table->longtext('residual_detectability')->nullable();
            $table->longtext('residual_rpn')->nullable();
            $table->longtext('risk_acceptance')->nullable();
            $table->longtext('risk_acceptance2')->nullable();
            $table->longtext('mitigation_proposal')->nullable();           

            $table->longtext('measurement')->nullable();
            $table->longtext('materials')->nullable();
            $table->longtext('environment')->nullable();
            $table->longtext('manpower')->nullable();
            $table->longtext('machine')->nullable();
            $table->longtext('methods')->nullable();
            $table->longtext('problem_statement')->nullable();

            $table->longtext('inference_type')->nullable();
            $table->longtext('inference_remarks')->nullable();

            $table->longtext('why_problem_statement')->nullable();
            $table->longtext('why_1')->nullable();
            $table->longtext('why_2')->nullable();
            $table->longtext('why_3')->nullable();
            $table->longtext('why_4')->nullable();
            $table->longtext('why_5')->nullable();
            $table->longtext('why_root_cause')->nullable();            

            $table->longtext('what_will_be')->nullable();
            $table->longtext('what_will_not_be')->nullable();
            $table->longtext('what_rationable')->nullable();
            $table->longtext('where_will_be')->nullable();
            $table->longtext('where_will_not_be')->nullable();
            $table->longtext('where_rationable')->nullable();
            $table->longtext('when_will_be')->nullable();
            $table->longtext('when_will_not_be')->nullable();
            $table->longtext('when_rationable')->nullable();
            $table->longtext('coverage_will_be')->nullable();
            $table->longtext('coverage_will_not_be')->nullable();
            $table->longtext('coverage_rationable')->nullable();
            $table->longtext('who_will_be')->nullable();
            $table->longtext('who_will_not_be')->nullable();
            $table->longtext('who_rationable')->nullable();

            $table->text('Submit_By')->nullable();
            $table->text('Submit_On')->nullable();
            $table->longText('Submit_Comment')->nullable();
            $table->text('Cancel_By')->nullable();
            $table->text('Cancel_On')->nullable();
            $table->longText('Cancel_Comment')->nullable();
            $table->text('Cancelled_By')->nullable();
            $table->text('Cancelled_On')->nullable();
            $table->longText('Cancelled_Comment')->nullable();
            $table->text('Review_Complete_By')->nullable();
            $table->text('Review_Complete_On')->nullable();
            $table->longText('Review_Complete_Comment')->nullable();
            $table->text('Complete_Investigation_By')->nullable();
            $table->text('Complete_Investigation_On')->nullable();
            $table->longText('Complete_Investigation_Comment')->nullable();
            $table->text('Analysis_Complete_By')->nullable();
            $table->text('Analysis_Complete_On')->nullable();
            $table->longText('Analysis_Complete_Comment')->nullable();
            $table->text('Propose_Plan_By')->nullable();
            $table->text('Propose_Plan_On')->nullable();
            $table->longText('Propose_Plan_Comment')->nullable();
            $table->text('Approve_Plan_By')->nullable();
            $table->text('Approve_Plan_On')->nullable();
            $table->longText('Approve_Plan_Comment')->nullable();
            $table->text('All_CAPA_Closed_By')->nullable();
            $table->text('All_CAPA_Closed_On')->nullable();
            $table->longText('All_CAPA_Closed_Comment')->nullable();
            $table->text('More_Info_Required_By')->nullable();
            $table->text('More_Info_Required_On')->nullable();
            $table->longText('More_Info_Required_Comment')->nullable();
            $table->text('More_Investigation_Req_By')->nullable();
            $table->text('More_Investigation_Req_On')->nullable();
            $table->longText('More_Investigation_Req_Comment')->nullable();
            $table->text('Reject_By')->nullable();
            $table->text('Reject_On')->nullable();
            $table->longText('Reject_Comment')->nullable();
            
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('e_h_s_events');
    }
};
